---
- name: DEBUG Display the virt_install_import var
  ansible.builtin.debug:
    var:
      virt_install_import
  tags:
    - debug
    - never

- name: Error if name is not defined
  ansible.builtin.fail:
    msg:
      - "Sorry, I need a name to continue"
  when:
    - virt_install_import.name is not defined

- name: Install virt-install related packages
  ansible.builtin.include_tasks: install.yml
  args:
    apply:
      tags:
        - install
  tags:
    - install

# Create the virt-install command

- name: Set _virt_install_cmd
  ansible.builtin.set_fact:
    _virt_install_cmd: >-
      virt-install --import --wait {{ virt_install_import.wait | default(0) }}
      --name {{ virt_install_import.name }}
      --memory {{ virt_install_import.memory | default(1024) }}
      --vcpus {{ virt_install_import.vcpu | default(1) }}
      --virt-type {{ virt_install_import.virt_type | default('kvm') }}
      --graphics {{ virt_install.graphics | default('none') }}

- name: Add autostart to the cmd
  ansible.builtin.set_fact:
    _virt_install_cmd:
      "{{ _virt_install_cmd }} --autostart"
  when:
    - virt_install_import.autostart|default(true)|bool

- name: Add os_type to the cmd if defined
  ansible.builtin.set_fact:
    _virt_install_cmd:
      "{{ _virt_install_cmd }} --os-type {{ virt_install_import.os_type }}"
  when:
    - virt_install_import.os_type is defined

- name: Add os_variant to the cmd if defined
  ansible.builtin.set_fact:
    _virt_install_cmd:
      "{{ _virt_install_cmd }} --os-variant {{ virt_install_import.os_variant }}"
  when:
    - virt_install_import.os_variant is defined

- name: Add network to the cmd if defined
  ansible.builtin.set_fact:
    _virt_install_cmd:
      "{{ _virt_install_cmd }} --network {{ virt_install_import.network }}"
  when:
    - virt_install_import.network is defined

- name: Add disks
  ansible.builtin.set_fact:
    _virt_install_cmd:
      "{{ _virt_install_cmd }} --disk {{ virt_disk }}"
  with_items: "{{ virt_install_import.disks | default([]) }}"
  loop_control:
    loop_var: virt_disk

- name: DEBUG Display _virt_install_cmd
  ansible.builtin.debug:
    var:
      _virt_install_cmd
  tags:
    - debug
    - never

- name: Run the _virt_install_cmd command
  ansible.builtin.command:
    "{{ _virt_install_cmd }}"
  register:
    _virt_install_cmd_result
  changed_when:
    _virt_install_cmd_result.rc == 0
  failed_when:
    _virt_install_cmd_result.rc != 0
